Neos:
  Flow:
    security:
      authentication:
        providers:
          'DefaultProvider':
            provider: 'PersistedUsernamePasswordProvider'
            entryPoint: 'WebRedirect'
            entryPointOptions:
              routeValues:
                '@package': 'KP.Lunch'
                '@controller': 'Login'
                '@action': 'index'
    mvc:
      # Defines routes that should be included after existing routes defined in the main Routes.yaml (if any)
      # Note: This only allows to include existing Routes.yaml files from other packages, you can't adjust the routes via Settings.
      #
      # Syntax:
      # 'Some.Package': TRUE
      # 'SomeOther.Package':
      #   position: 'after Some.Package'
      #
      routes: []            
    